# Generated by Django 4.0.1 on 2022-01-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedNotepad",
            fields=[
                (
                    "name",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("value", models.TextField()),
            ],
        ),
    ]
